/**
 * The shared hourly edition.
 *
 * One passage and one interpretation per hour, produced once and served to
 * every visitor. This exists because generating in the browser gave each
 * reader a different interpretation of the same verse -- two devices open on
 * the same hour disagreed about what the passage meant, and every visit spent
 * more of the NVIDIA quota.
 *
 * How sharing is achieved without a database: selection is a seeded PRNG keyed
 * on (hour, slot), so it is reproducible rather than stored, and the response
 * is cached at Vercel's CDN for the rest of the hour. The first visitor of an
 * hour pays for the generation; everyone after that is served the identical
 * bytes from the edge.
 *
 * NOTE ON STRUCTURE: this file is deliberately self-contained and imports
 * nothing. Vercel does not bundle imports for api/ functions -- neither
 * `../src/...` nor even `./_lib/...` -- both fail at runtime with
 * ERR_MODULE_NOT_FOUND. The canon table below is generated from
 * src/data/ethiopianCanon.ts by `npm run gen:api-canon` so it cannot drift.
 */

export const config = { runtime: 'nodejs', maxDuration: 60 };

type Section = 'protocanonical' | 'deuterocanonical' | 'ethiopian';
type Slot = 'verse' | 'passage' | 'ethiopian';

interface CompactPart {
  /** 'a' = bible-api.com, 'g' = the Ge'ez dataset on jsDelivr. */
  k: 'a' | 'g';
  b: string;
  l: string;
  c: number;
  e?: 'full' | 'partial' | 'none';
}

interface CompactBook {
  i: string;
  n: string;
  g?: string;
  s: Section;
  t: 'old' | 'new';
  p: CompactPart[];
}

// <generated-canon>
// Generated by scripts/gen-api-canon.mjs from src/data/ethiopianCanon.ts.
// Do not edit by hand; run `npm run gen:api-canon` after changing the canon.
const CANON: CompactBook[] = [
  {
    "i": "genesis",
    "n": "Genesis",
    "g": "ኦሪት ዘፍጥረት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "GEN",
        "l": "Genesis",
        "c": 50
      }
    ]
  },
  {
    "i": "exodus",
    "n": "Exodus",
    "g": "ኦሪት ዘጸአት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "EXO",
        "l": "Exodus",
        "c": 40
      }
    ]
  },
  {
    "i": "leviticus",
    "n": "Leviticus",
    "g": "ኦሪት ዘሌዋውያን",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "LEV",
        "l": "Leviticus",
        "c": 27
      }
    ]
  },
  {
    "i": "numbers",
    "n": "Numbers",
    "g": "ኦሪት ዘሱሦ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "NUM",
        "l": "Numbers",
        "c": 36
      }
    ]
  },
  {
    "i": "deuteronomy",
    "n": "Deuteronomy",
    "g": "ኦሪት ዘዳግም",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "DEU",
        "l": "Deuteronomy",
        "c": 34
      }
    ]
  },
  {
    "i": "joshua",
    "n": "Joshua",
    "g": "መጽሐፈ ኢያሱ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JOS",
        "l": "Joshua",
        "c": 24
      }
    ]
  },
  {
    "i": "judges",
    "n": "Judges",
    "g": "መጽሐፈ መሳፍንት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JDG",
        "l": "Judges",
        "c": 21
      }
    ]
  },
  {
    "i": "ruth",
    "n": "Ruth",
    "g": "መጽሐፈ ሩት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "RUT",
        "l": "Ruth",
        "c": 4
      }
    ]
  },
  {
    "i": "samuel",
    "n": "I and II Samuel",
    "g": "መጽሐፈ ሳሙኤል",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "1SA",
        "l": "1 Samuel",
        "c": 31
      },
      {
        "k": "a",
        "b": "2SA",
        "l": "2 Samuel",
        "c": 24
      }
    ]
  },
  {
    "i": "kings",
    "n": "I and II Kings",
    "g": "መጽሐፈ ነገሥት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "1KI",
        "l": "1 Kings",
        "c": 22
      },
      {
        "k": "a",
        "b": "2KI",
        "l": "2 Kings",
        "c": 25
      }
    ]
  },
  {
    "i": "1-chronicles",
    "n": "I Chronicles",
    "g": "መጽሐፈ ዜና መዋዕል ቀዳማዊ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "1CH",
        "l": "1 Chronicles",
        "c": 29
      }
    ]
  },
  {
    "i": "2-chronicles",
    "n": "II Chronicles",
    "g": "መጽሐፈ ዜና መዋዕል ካልዕ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "2CH",
        "l": "2 Chronicles",
        "c": 36
      }
    ]
  },
  {
    "i": "jubilees",
    "n": "Jubilees",
    "g": "መጽሐፈ ኩፋሌ",
    "s": "ethiopian",
    "t": "old",
    "p": [
      {
        "k": "g",
        "b": "Jub",
        "l": "Jubilees",
        "c": 50,
        "e": "partial"
      }
    ]
  },
  {
    "i": "enoch",
    "n": "Enoch",
    "g": "መጽሐፈ ሄኖክ",
    "s": "ethiopian",
    "t": "old",
    "p": [
      {
        "k": "g",
        "b": "1En",
        "l": "1 Enoch",
        "c": 108,
        "e": "full"
      }
    ]
  },
  {
    "i": "ezra-nehemiah",
    "n": "Ezra and Nehemiah",
    "g": "ዕዝራ ወነሐምያ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "EZR",
        "l": "Ezra",
        "c": 10
      },
      {
        "k": "a",
        "b": "NEH",
        "l": "Nehemiah",
        "c": 13
      }
    ]
  },
  {
    "i": "ezra-sutuel",
    "n": "Ezra (2nd) and Ezra Sutuel",
    "g": "መጽሐፈ ዕዝራ ሱቱኤል",
    "s": "deuterocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "1ES",
        "l": "1 Esdras",
        "c": 9
      },
      {
        "k": "a",
        "b": "2ES",
        "l": "2 Esdras",
        "c": 16
      }
    ]
  },
  {
    "i": "tobit",
    "n": "Tobit",
    "g": "መጽሐፈ ጠቦቲ",
    "s": "deuterocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "TOB",
        "l": "Tobit",
        "c": 14
      }
    ]
  },
  {
    "i": "judith",
    "n": "Judith",
    "g": "መጽሐፈ ዮዲት",
    "s": "deuterocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JDT",
        "l": "Judith",
        "c": 16
      }
    ]
  },
  {
    "i": "esther",
    "n": "Esther",
    "g": "መጽሐፈ አስቴር",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "EST",
        "l": "Esther",
        "c": 10
      }
    ]
  },
  {
    "i": "1-meqabyan",
    "n": "1 Meqabyan",
    "g": "መጽሐፈ መቃብያን ቀዳማዊ",
    "s": "ethiopian",
    "t": "old",
    "p": [
      {
        "k": "g",
        "b": "1Meq",
        "l": "1 Meqabyan",
        "c": 36,
        "e": "none"
      }
    ]
  },
  {
    "i": "2-3-meqabyan",
    "n": "II and III Meqabyan",
    "g": "መጽሐፈ መቃብያን ካልእ ወሳልስ",
    "s": "ethiopian",
    "t": "old",
    "p": [
      {
        "k": "g",
        "b": "3Meq",
        "l": "3 Meqabyan",
        "c": 10,
        "e": "none"
      }
    ]
  },
  {
    "i": "job",
    "n": "Job",
    "g": "መጽሐፈ ኢዮብ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JOB",
        "l": "Job",
        "c": 42
      }
    ]
  },
  {
    "i": "psalms",
    "n": "Psalms",
    "g": "መዝሙረ ዳዊት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "PSA",
        "l": "Psalms",
        "c": 150
      }
    ]
  },
  {
    "i": "proverbs",
    "n": "Proverbs",
    "g": "መጽሐፈ ምሳሌ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "PRO",
        "l": "Proverbs",
        "c": 31
      }
    ]
  },
  {
    "i": "wisdom",
    "n": "Metsihafe Tibeb (Wisdom)",
    "g": "መጽሐፈ ጥበብ",
    "s": "deuterocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "WIS",
        "l": "Wisdom of Solomon",
        "c": 19
      }
    ]
  },
  {
    "i": "ecclesiastes",
    "n": "Ecclesiastes",
    "g": "መጽሐፈ መክብብ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "ECC",
        "l": "Ecclesiastes",
        "c": 12
      }
    ]
  },
  {
    "i": "song-of-songs",
    "n": "The Song of Songs",
    "g": "ማሕልየ መሓልይ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "SNG",
        "l": "Song of Solomon",
        "c": 8
      }
    ]
  },
  {
    "i": "isaiah",
    "n": "Isaiah",
    "g": "ትንቢት ኢሳይያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "ISA",
        "l": "Isaiah",
        "c": 66
      }
    ]
  },
  {
    "i": "jeremiah",
    "n": "Jeremiah",
    "g": "ትንቢት ኤርምያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JER",
        "l": "Jeremiah",
        "c": 52
      },
      {
        "k": "a",
        "b": "LAM",
        "l": "Lamentations",
        "c": 5
      },
      {
        "k": "a",
        "b": "BAR",
        "l": "Baruch",
        "c": 5
      }
    ]
  },
  {
    "i": "ezekiel",
    "n": "Ezekiel",
    "g": "ትንቢት ሄዜቅኤል",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "EZK",
        "l": "Ezekiel",
        "c": 48
      }
    ]
  },
  {
    "i": "daniel",
    "n": "Daniel",
    "g": "ትንቢት ዳንኤል",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "DAN",
        "l": "Daniel",
        "c": 12
      },
      {
        "k": "a",
        "b": "SUS",
        "l": "Susanna",
        "c": 1
      },
      {
        "k": "a",
        "b": "BEL",
        "l": "Bel and the Dragon",
        "c": 1
      },
      {
        "k": "a",
        "b": "S3Y",
        "l": "The Prayer of Azariah",
        "c": 1
      }
    ]
  },
  {
    "i": "hosea",
    "n": "Hosea",
    "g": "ትንቢት ሆሴዕ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "HOS",
        "l": "Hosea",
        "c": 14
      }
    ]
  },
  {
    "i": "amos",
    "n": "Amos",
    "g": "ትንቢት አሞጽ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "AMO",
        "l": "Amos",
        "c": 9
      }
    ]
  },
  {
    "i": "micah",
    "n": "Micah",
    "g": "ትንቢት ሚኪያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "MIC",
        "l": "Micah",
        "c": 7
      }
    ]
  },
  {
    "i": "joel",
    "n": "Joel",
    "g": "ትንቢት ኢያኤል",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JOL",
        "l": "Joel",
        "c": 3
      }
    ]
  },
  {
    "i": "obadiah",
    "n": "Obadiah",
    "g": "ትንቢት አብዲዮ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "OBA",
        "l": "Obadiah",
        "c": 1
      }
    ]
  },
  {
    "i": "jonah",
    "n": "Jonah",
    "g": "ትንቢት ዮናስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JON",
        "l": "Jonah",
        "c": 4
      }
    ]
  },
  {
    "i": "nahum",
    "n": "Nahum",
    "g": "ትንቢት ናዘም",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "NAM",
        "l": "Nahum",
        "c": 3
      }
    ]
  },
  {
    "i": "habakkuk",
    "n": "Habakkuk",
    "g": "ትንቢት እንባቁም",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "HAB",
        "l": "Habakkuk",
        "c": 3
      }
    ]
  },
  {
    "i": "zephaniah",
    "n": "Zephaniah",
    "g": "ትንቢት ሶፈኒያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "ZEP",
        "l": "Zephaniah",
        "c": 3
      }
    ]
  },
  {
    "i": "haggai",
    "n": "Haggai",
    "g": "ትንቢት ሓጊ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "HAG",
        "l": "Haggai",
        "c": 2
      }
    ]
  },
  {
    "i": "zechariah",
    "n": "Zechariah",
    "g": "ትንቢት ዘካርያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "ZEC",
        "l": "Zechariah",
        "c": 14
      }
    ]
  },
  {
    "i": "malachi",
    "n": "Malachi",
    "g": "ትንቢት ሚልኪያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "MAL",
        "l": "Malachi",
        "c": 4
      }
    ]
  },
  {
    "i": "sirach",
    "n": "Sirach",
    "g": "መጽሐፈ ሲራክ",
    "s": "deuterocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "SIR",
        "l": "Sirach",
        "c": 51
      }
    ]
  },
  {
    "i": "matthew",
    "n": "Matthew",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "MAT",
        "l": "Matthew",
        "c": 28
      }
    ]
  },
  {
    "i": "mark",
    "n": "Mark",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "MRK",
        "l": "Mark",
        "c": 16
      }
    ]
  },
  {
    "i": "luke",
    "n": "Luke",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "LUK",
        "l": "Luke",
        "c": 24
      }
    ]
  },
  {
    "i": "john",
    "n": "John",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "JHN",
        "l": "John",
        "c": 21
      }
    ]
  },
  {
    "i": "acts",
    "n": "Acts",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "ACT",
        "l": "Acts",
        "c": 28
      }
    ]
  },
  {
    "i": "romans",
    "n": "Romans",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "ROM",
        "l": "Romans",
        "c": 16
      }
    ]
  },
  {
    "i": "1-corinthians",
    "n": "1 Corinthians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "1CO",
        "l": "1 Corinthians",
        "c": 16
      }
    ]
  },
  {
    "i": "2-corinthians",
    "n": "2 Corinthians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "2CO",
        "l": "2 Corinthians",
        "c": 13
      }
    ]
  },
  {
    "i": "galatians",
    "n": "Galatians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "GAL",
        "l": "Galatians",
        "c": 6
      }
    ]
  },
  {
    "i": "ephesians",
    "n": "Ephesians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "EPH",
        "l": "Ephesians",
        "c": 6
      }
    ]
  },
  {
    "i": "philippians",
    "n": "Philippians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "PHP",
        "l": "Philippians",
        "c": 4
      }
    ]
  },
  {
    "i": "colossians",
    "n": "Colossians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "COL",
        "l": "Colossians",
        "c": 4
      }
    ]
  },
  {
    "i": "1-thessalonians",
    "n": "1 Thessalonians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "1TH",
        "l": "1 Thessalonians",
        "c": 5
      }
    ]
  },
  {
    "i": "2-thessalonians",
    "n": "2 Thessalonians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "2TH",
        "l": "2 Thessalonians",
        "c": 3
      }
    ]
  },
  {
    "i": "1-timothy",
    "n": "1 Timothy",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "1TI",
        "l": "1 Timothy",
        "c": 6
      }
    ]
  },
  {
    "i": "2-timothy",
    "n": "2 Timothy",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "2TI",
        "l": "2 Timothy",
        "c": 4
      }
    ]
  },
  {
    "i": "titus",
    "n": "Titus",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "TIT",
        "l": "Titus",
        "c": 3
      }
    ]
  },
  {
    "i": "philemon",
    "n": "Philemon",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "PHM",
        "l": "Philemon",
        "c": 1
      }
    ]
  },
  {
    "i": "hebrews",
    "n": "Hebrews",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "HEB",
        "l": "Hebrews",
        "c": 13
      }
    ]
  },
  {
    "i": "james",
    "n": "James",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "JAS",
        "l": "James",
        "c": 5
      }
    ]
  },
  {
    "i": "1-peter",
    "n": "1 Peter",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "1PE",
        "l": "1 Peter",
        "c": 5
      }
    ]
  },
  {
    "i": "2-peter",
    "n": "2 Peter",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "2PE",
        "l": "2 Peter",
        "c": 3
      }
    ]
  },
  {
    "i": "1-john",
    "n": "1 John",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "1JN",
        "l": "1 John",
        "c": 5
      }
    ]
  },
  {
    "i": "2-john",
    "n": "2 John",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "2JN",
        "l": "2 John",
        "c": 1
      }
    ]
  },
  {
    "i": "3-john",
    "n": "3 John",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "3JN",
        "l": "3 John",
        "c": 1
      }
    ]
  },
  {
    "i": "jude",
    "n": "Jude",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "JUD",
        "l": "Jude",
        "c": 1
      }
    ]
  },
  {
    "i": "revelation",
    "n": "Revelation",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "REV",
        "l": "Revelation",
        "c": 22
      }
    ]
  },
  {
    "i": "sirate-tsion",
    "n": "Sirate Tsion (Order of Zion)",
    "g": "ስርዓተ ጽይዎን",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "Sinod",
        "l": "Sinodos",
        "c": 36,
        "e": "none"
      }
    ]
  },
  {
    "i": "tizaz",
    "n": "Tizaz (The Commandment)",
    "g": "ትዕዛዝ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "Sinod",
        "l": "Sinodos",
        "c": 36,
        "e": "none"
      }
    ]
  },
  {
    "i": "gitsew",
    "n": "Gitsew",
    "g": "ግጽወ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "Sinod",
        "l": "Sinodos",
        "c": 36,
        "e": "none"
      }
    ]
  },
  {
    "i": "abtilis",
    "n": "Abtilis",
    "g": "አብትሊስ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "Sinod",
        "l": "Sinodos",
        "c": 36,
        "e": "none"
      }
    ]
  },
  {
    "i": "1-dominos",
    "n": "The I Book of Dominos",
    "g": "ኪዳን ዘእግዚእነ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "TestLd",
        "l": "Testament of Our Lord",
        "c": 60,
        "e": "none"
      }
    ]
  },
  {
    "i": "2-dominos",
    "n": "The II Book of Dominos",
    "g": "ኪዳን ዘእግዚእነ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "TestLd",
        "l": "Testament of Our Lord",
        "c": 60,
        "e": "none"
      }
    ]
  },
  {
    "i": "clement",
    "n": "The Book of Clement",
    "g": "ቀሌሜንጥስ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "Clem",
        "l": "Ethiopic Clement",
        "c": 67,
        "e": "none"
      }
    ]
  }
];
// </generated-canon>

const BIBLE_API = 'https://bible-api.com';
const GEEZ_DATA = 'https://cdn.jsdelivr.net/gh/LPettay/ethiopian-bible@main/public/data/chapters';

/**
 * Ordered by how quickly they finish, because the whole generation has to fit
 * inside the 60s function limit. Measured on a three-paragraph interpretation:
 * super-120b ~19s, nano ~7s, gpt-oss ~7s. The 550B Ultra model used in the
 * browser takes one to three minutes and cannot be used here.
 */
const MODELS = [
  { id: 'nvidia/nemotron-3-super-120b-a12b', label: 'Nemotron 3 Super', prefix: 'detailed thinking off\n\n' },
  { id: 'openai/gpt-oss-120b', label: 'GPT-OSS 120B', prefix: '' },
  { id: 'nvidia/nemotron-3-nano-30b-a3b', label: 'Nemotron 3 Nano', prefix: 'detailed thinking off\n\n' },
];

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const clean = (value: unknown): string => (typeof value === 'string' ? value.trim() : '');

/** Stable 32-bit PRNG: the same hour and slot select the same text everywhere. */
function seededRandom(seed: string): () => number {
  let hash = 2166136261;
  for (let index = 0; index < seed.length; index += 1) {
    hash ^= seed.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  let state = hash >>> 0;
  return () => {
    state += 0x6d2b79f5;
    let value = state;
    value = Math.imul(value ^ (value >>> 15), value | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
  };
}

export interface HourlyContent {
  text: string;
  reference: string;
  translation_id: string;
  translation_name: string;
  book_id: string;
  book_name: string;
  chapter: number;
  verse: number;
  type: 'verse' | 'passage';
  testament: 'old' | 'new';
  book: string;
  section: Section;
  geezName?: string;
  context?: { before: string; after: string; chapterReference: string };
}

/**
 * Picks and loads the passage for one (hour, slot). Deterministic: given the
 * same inputs it always resolves to the same verses.
 */
class EditionSelector {
  private readonly random: () => number;

  constructor(
    hour: string,
    private readonly slot: Slot,
  ) {
    this.random = seededRandom(`${hour}:${slot}`);
  }

  /** Books eligible for this slot, excluding any with no English to show. */
  private candidates(): CompactBook[] {
    const readable = (book: CompactBook) =>
      book.p.some((part) => part.k === 'a' || part.e !== 'none');

    if (this.slot === 'ethiopian') {
      return CANON.filter((book) => book.s !== 'protocanonical' && readable(book));
    }
    return CANON.filter(readable);
  }

  /** Chapters we can show English for, as a prefix of the book's range. */
  private translatableChapters(book: CompactBook): number {
    let total = 0;
    for (const part of book.p) {
      if (part.k === 'g' && part.e === 'none') break;
      total += part.c;
    }
    return total;
  }

  private pickBook(): CompactBook {
    const books = this.candidates();
    const weights = books.map((book) => this.translatableChapters(book));
    const total = weights.reduce((sum, weight) => sum + weight, 0);

    let target = this.random() * total;
    for (let index = 0; index < books.length; index += 1) {
      target -= weights[index];
      if (target <= 0) return books[index];
    }
    return books[books.length - 1];
  }

  private resolve(book: CompactBook, chapter: number): { part: CompactPart; local: number } {
    let remaining = chapter;
    for (const part of book.p) {
      if (remaining <= part.c) return { part, local: remaining };
      remaining -= part.c;
    }
    return { part: book.p[0], local: 1 };
  }

  async load(): Promise<HourlyContent> {
    const book = this.pickBook();
    const span = this.translatableChapters(book);
    const chapter = 1 + Math.floor(this.random() * span);
    const { part, local } = this.resolve(book, chapter);

    const verses = part.k === 'a'
      ? await this.loadFromBibleApi(part, local)
      : await this.loadFromGeez(part, local);

    const usable = verses.filter((verse) => verse.text.length > 0);
    if (usable.length === 0) throw new Error(`${book.n} ${chapter} has no readable text`);

    // The passage slot shows a run of verses; the others show one.
    const wanted = this.slot === 'passage' ? Math.min(6, usable.length) : 1;
    const start = Math.floor(this.random() * (usable.length - wanted + 1));
    const chosen = usable.slice(start, start + wanted);
    const first = chosen[0];
    const last = chosen[chosen.length - 1];

    const reference = chosen.length === 1
      ? `${part.l} ${local}:${first.verse}`
      : `${part.l} ${local}:${first.verse}-${last.verse}`;

    const index = usable.indexOf(first);
    const join = (list: typeof usable) => list.map((verse) => verse.text).join(' ');

    return {
      text: chosen.map((verse) => verse.text).join(' '),
      reference,
      translation_id: part.k === 'a' ? 'kjv' : 'geez',
      translation_name: part.k === 'a' ? 'King James Version' : 'Ge’ez sources',
      book_id: part.b,
      book_name: part.l,
      chapter: local,
      verse: first.verse,
      type: this.slot === 'passage' ? 'passage' : 'verse',
      testament: book.t,
      book: part.l,
      section: book.s,
      geezName: book.g,
      context: {
        before: join(usable.slice(Math.max(0, index - 4), index)),
        after: join(usable.slice(index + chosen.length, index + chosen.length + 4)),
        chapterReference: `${part.l} ${local}`,
      },
    };
  }

  private async loadFromBibleApi(part: CompactPart, chapter: number) {
    const response = await fetch(`${BIBLE_API}/data/kjv/${part.b}/${chapter}`);
    if (!response.ok) throw new Error(`bible-api ${response.status} for ${part.b} ${chapter}`);
    const data = (await response.json()) as { verses?: Array<{ text?: string; verse?: number }> };
    return (data.verses ?? []).map((verse, index) => ({
      verse: verse.verse ?? index + 1,
      text: clean(verse.text),
    }));
  }

  private async loadFromGeez(part: CompactPart, chapter: number) {
    const response = await fetch(`${GEEZ_DATA}/${part.b}/${chapter}.json`);
    if (!response.ok) throw new Error(`jsDelivr ${response.status} for ${part.b} ${chapter}`);
    const data = (await response.json()) as {
      verses?: Array<{
        num: number | string;
        translation?: string;
        translations?: { lxx?: string; kjv?: string };
      }>;
    };
    return (data.verses ?? []).map((verse) => ({
      verse: Number(verse.num),
      text:
        clean(verse.translation) ||
        clean(verse.translations?.lxx) ||
        clean(verse.translations?.kjv),
    }));
  }
}

/** Generates the interpretation, walking the model list until one answers. */
class Interpreter {
  constructor(private readonly apiKey: string) {}

  private messages(content: HourlyContent): { system: string; user: string } {
    const geez = content.geezName ? ` Its Ge’ez title is ${content.geezName}.` : '';
    const canon =
      content.section === 'ethiopian'
        ? ` This passage is from a book canonical in the Ethiopian Orthodox Tewahedo Church and not found in the Protestant or Catholic canons.${geez} Interpret it from within that tradition, noting briefly why it is received there.`
        : content.section === 'deuterocanonical'
          ? ` This passage is deuterocanonical: received by the Ethiopian Orthodox Tewahedo, Catholic, and Eastern Orthodox churches, though not in the Protestant canon.${geez}`
          : geez;

    const system = `You are a biblical scholar and historian writing for a reader of the Ethiopian Orthodox Tewahedo Bible. You know the historical setting of each book, the literary shape of its argument, and the tradition that received it.${canon}

Write three short paragraphs, with no headings and no bullet points. First, place the passage in its historical setting, naming the period, place, audience, and relevant political or religious pressure where known. Second, explain what happens in the supplied surrounding verses and how the passage connects to them, including an original-language detail or custom only when it materially helps. Third, draw out its meaning for a reader today, grounded in that setting. Be specific; do not write generic encouragement or merely restate the verse. State uncertainty rather than inventing detail.`;

    let user = `Interpret this Bible ${content.type} from ${content.reference}:\n\n"${content.text}"`;
    if (content.context?.before || content.context?.after) {
      user += `\n\nSurrounding text from ${content.context.chapterReference}:`;
      if (content.context.before) user += `\n\nImmediately before:\n"${content.context.before}"`;
      if (content.context.after) user += `\n\nImmediately after:\n"${content.context.after}"`;
      user += '\n\nUse this context, but interpret only the selected passage.';
    }

    return { system, user };
  }

  private transient(status: number, message: string): boolean {
    return (
      status === 429 ||
      status >= 500 ||
      /overload|temporarily unavailable|not ready to serve|try again|capacity|timed? ?out/i.test(message)
    );
  }

  async run(content: HourlyContent, deadline: number) {
    const { system, user } = this.messages(content);
    let lastError = 'no model attempted';

    for (const model of MODELS) {
      for (let attempt = 1; attempt <= 2; attempt += 1) {
        if (Date.now() > deadline) throw new Error('Out of time generating interpretation');

        try {

        // Bound each attempt so one slow model cannot consume the whole 60s
        // function budget. Measured generations are 7-20s locally but run
        // longer from Vercel's region, so the cap is 32s -- past that, the
        // remaining budget is better spent on the next (faster) model.
        const remaining = Math.max(1000, Math.min(32_000, deadline - Date.now()));

        const response = await fetch('https://integrate.api.nvidia.com/v1/chat/completions', {
          method: 'POST',
          signal: AbortSignal.timeout(remaining),
          headers: {
            Authorization: `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            model: model.id,
            messages: [
              { role: 'system', content: model.prefix + system },
              { role: 'user', content: user },
            ],
            max_tokens: 2048,
            temperature: 0.7,
          }),
        });

        if (!response.ok) {
          lastError = `${model.id}: HTTP ${response.status}`;
          const body = (await response.text()).slice(0, 200);
          if (this.transient(response.status, body) && attempt === 1) {
            await sleep(2000);
            continue;
          }
          break;
        }

        const data = (await response.json()) as {
          choices?: Array<{ message?: { content?: string } }>;
        };
        const text = clean(data.choices?.[0]?.message?.content);
        if (text) return { text, model: { id: model.id, label: model.label } };

        lastError = `${model.id}: empty response`;
        } catch (error) {
          // Includes the per-attempt timeout above; move on to the next model.
          lastError = `${model.id}: ${(error as Error).message}`;
          break;
        }
      }
    }

    throw new Error(lastError);
  }
}

/** Collapses concurrent requests for the same edition into one generation. */
const inflight = new Map<string, Promise<unknown>>();

function once<T>(key: string, factory: () => Promise<T>): Promise<T> {
  const running = inflight.get(key);
  if (running) return running as Promise<T>;
  const promise = factory().finally(() => inflight.delete(key));
  inflight.set(key, promise);
  return promise;
}

function hourKey(date = new Date()): string {
  return date.toISOString().slice(0, 13);
}

function json(body: unknown, status = 200, shareable = false): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'Content-Type': 'application/json',
      // The CDN copy is what makes the edition shared: one generation per
      // hour is reused for every visitor until the hour rolls over.
      'Cache-Control': shareable ? 'public, max-age=60' : 'no-store',
      ...(shareable
        ? { 'Vercel-CDN-Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400, stale-if-error=86400' }
        : {}),
    },
  });
}

/**
 * Exported as a named `GET` rather than `export default`.
 *
 * Under Vercel's Node runtime a default export is treated as the legacy
 * `(req, res) => void` signature and any returned `Response` is silently
 * discarded -- the function then never responds and is killed at the 60s
 * timeout. A named HTTP-method export opts into the Web fetch-style API.
 */
export async function GET(request: Request): Promise<Response> {
  const deadline = Date.now() + 55_000;
  // Under Vercel's Node runtime `request.url` is a path ("/api/hourly?..."),
  // not an absolute URL as it would be on the edge runtime, so URL needs a
  // base to parse against.
  const url = new URL(request.url, 'http://localhost');
  const slot = (url.searchParams.get('slot') ?? 'verse') as Slot;
  const requested = url.searchParams.get('hour') ?? hourKey();

  if (!['verse', 'passage', 'ethiopian'].includes(slot)) {
    return json({ error: 'Unknown slot' }, 400);
  }

  // Only the current or previous hour, so a crawler cannot walk arbitrary keys
  // and manufacture unlimited model calls.
  const now = hourKey();
  const previous = hourKey(new Date(Date.now() - 3600_000));
  if (requested !== now && requested !== previous) {
    return json({ error: 'Edition expired' }, 400);
  }

  try {
    const content = await once(`content:${requested}:${slot}`, () =>
      new EditionSelector(requested, slot).load(),
    );

    if (!process.env.NVIDIA_API_KEY) {
      return json({ hour: requested, slot, content, interpretation: null }, 200, true);
    }

    const interpretation = await once(`interpretation:${requested}:${slot}`, () =>
      new Interpreter(process.env.NVIDIA_API_KEY as string).run(content, deadline),
    ).catch((error: Error) => {
      console.warn('Interpretation failed:', error.message);
      return null;
    });

    // Only a complete edition is allowed into the shared CDN cache. Caching a
    // failed generation would freeze "interpretation unavailable" in place for
    // the rest of the hour for every visitor; leaving it uncached lets the next
    // request try again.
    return json({ hour: requested, slot, content, interpretation }, 200, interpretation !== null);
  } catch (error) {
    return json({ error: (error as Error).message }, 502);
  }
}
