/**
 * The shared edition.
 *
 * One reading and one interpretation per edition key, produced once and served
 * to every visitor. This exists because generating in the browser gave each
 * reader a different interpretation of the same verse -- two devices open at
 * the same time disagreed about what the passage meant, and every visit spent
 * more of the NVIDIA quota.
 *
 * Two cadences share this one function, decided by CADENCE below. The `verse`
 * and `ethiopian` slots turn over hourly. The `passage` slot turns over once a
 * day at 6am America/New_York, because it is the reading a family studies
 * together and is pushed to WhatsApp each morning -- an hourly passage is too
 * fast to sit with.
 *
 * How sharing is achieved without a database: selection is a seeded PRNG keyed
 * on (key, slot), so it is reproducible rather than stored, and the response
 * is cached at Vercel's CDN until that key rolls over. The first visitor of an
 * edition pays for the generation; everyone after that is served the identical
 * bytes from the edge.
 *
 * NOTE ON STRUCTURE: this file is deliberately self-contained and imports
 * nothing. Vercel does not bundle imports for api/ functions -- neither
 * `../src/...` nor even `./_lib/...` -- both fail at runtime with
 * ERR_MODULE_NOT_FOUND. The canon table below is generated from
 * src/data/ethiopianCanon.ts by `npm run gen:api-canon` so it cannot drift.
 */

export const config = { runtime: 'nodejs', maxDuration: 60 };

type Section = 'protocanonical' | 'deuterocanonical' | 'ethiopian';
type Slot = 'verse' | 'passage' | 'ethiopian';

interface CompactPart {
  /** 'a' = bible-api.com, 'g' = the Ge'ez dataset on jsDelivr. */
  k: 'a' | 'g';
  b: string;
  l: string;
  c: number;
  e?: 'full' | 'partial' | 'none';
}

interface CompactBook {
  i: string;
  n: string;
  g?: string;
  s: Section;
  t: 'old' | 'new';
  p: CompactPart[];
}

// <generated-canon>
// Generated by scripts/gen-api-canon.mjs from src/data/ethiopianCanon.ts.
// Do not edit by hand; run `npm run gen:api-canon` after changing the canon.
const CANON: CompactBook[] = [
  {
    "i": "genesis",
    "n": "Genesis",
    "g": "ኦሪት ዘፍጥረት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "GEN",
        "l": "Genesis",
        "c": 50
      }
    ]
  },
  {
    "i": "exodus",
    "n": "Exodus",
    "g": "ኦሪት ዘጸአት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "EXO",
        "l": "Exodus",
        "c": 40
      }
    ]
  },
  {
    "i": "leviticus",
    "n": "Leviticus",
    "g": "ኦሪት ዘሌዋውያን",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "LEV",
        "l": "Leviticus",
        "c": 27
      }
    ]
  },
  {
    "i": "numbers",
    "n": "Numbers",
    "g": "ኦሪት ዘሱሦ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "NUM",
        "l": "Numbers",
        "c": 36
      }
    ]
  },
  {
    "i": "deuteronomy",
    "n": "Deuteronomy",
    "g": "ኦሪት ዘዳግም",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "DEU",
        "l": "Deuteronomy",
        "c": 34
      }
    ]
  },
  {
    "i": "joshua",
    "n": "Joshua",
    "g": "መጽሐፈ ኢያሱ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JOS",
        "l": "Joshua",
        "c": 24
      }
    ]
  },
  {
    "i": "judges",
    "n": "Judges",
    "g": "መጽሐፈ መሳፍንት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JDG",
        "l": "Judges",
        "c": 21
      }
    ]
  },
  {
    "i": "ruth",
    "n": "Ruth",
    "g": "መጽሐፈ ሩት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "RUT",
        "l": "Ruth",
        "c": 4
      }
    ]
  },
  {
    "i": "samuel",
    "n": "I and II Samuel",
    "g": "መጽሐፈ ሳሙኤል",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "1SA",
        "l": "1 Samuel",
        "c": 31
      },
      {
        "k": "a",
        "b": "2SA",
        "l": "2 Samuel",
        "c": 24
      }
    ]
  },
  {
    "i": "kings",
    "n": "I and II Kings",
    "g": "መጽሐፈ ነገሥት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "1KI",
        "l": "1 Kings",
        "c": 22
      },
      {
        "k": "a",
        "b": "2KI",
        "l": "2 Kings",
        "c": 25
      }
    ]
  },
  {
    "i": "1-chronicles",
    "n": "I Chronicles",
    "g": "መጽሐፈ ዜና መዋዕል ቀዳማዊ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "1CH",
        "l": "1 Chronicles",
        "c": 29
      }
    ]
  },
  {
    "i": "2-chronicles",
    "n": "II Chronicles",
    "g": "መጽሐፈ ዜና መዋዕል ካልዕ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "2CH",
        "l": "2 Chronicles",
        "c": 36
      }
    ]
  },
  {
    "i": "jubilees",
    "n": "Jubilees",
    "g": "መጽሐፈ ኩፋሌ",
    "s": "ethiopian",
    "t": "old",
    "p": [
      {
        "k": "g",
        "b": "Jub",
        "l": "Jubilees",
        "c": 50,
        "e": "partial"
      }
    ]
  },
  {
    "i": "enoch",
    "n": "Enoch",
    "g": "መጽሐፈ ሄኖክ",
    "s": "ethiopian",
    "t": "old",
    "p": [
      {
        "k": "g",
        "b": "1En",
        "l": "1 Enoch",
        "c": 108,
        "e": "full"
      }
    ]
  },
  {
    "i": "ezra-nehemiah",
    "n": "Ezra and Nehemiah",
    "g": "ዕዝራ ወነሐምያ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "EZR",
        "l": "Ezra",
        "c": 10
      },
      {
        "k": "a",
        "b": "NEH",
        "l": "Nehemiah",
        "c": 13
      }
    ]
  },
  {
    "i": "ezra-sutuel",
    "n": "Ezra (2nd) and Ezra Sutuel",
    "g": "መጽሐፈ ዕዝራ ሱቱኤል",
    "s": "deuterocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "1ES",
        "l": "1 Esdras",
        "c": 9
      },
      {
        "k": "a",
        "b": "2ES",
        "l": "2 Esdras",
        "c": 16
      }
    ]
  },
  {
    "i": "tobit",
    "n": "Tobit",
    "g": "መጽሐፈ ጠቦቲ",
    "s": "deuterocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "TOB",
        "l": "Tobit",
        "c": 14
      }
    ]
  },
  {
    "i": "judith",
    "n": "Judith",
    "g": "መጽሐፈ ዮዲት",
    "s": "deuterocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JDT",
        "l": "Judith",
        "c": 16
      }
    ]
  },
  {
    "i": "esther",
    "n": "Esther",
    "g": "መጽሐፈ አስቴር",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "EST",
        "l": "Esther",
        "c": 10
      }
    ]
  },
  {
    "i": "1-meqabyan",
    "n": "1 Meqabyan",
    "g": "መጽሐፈ መቃብያን ቀዳማዊ",
    "s": "ethiopian",
    "t": "old",
    "p": [
      {
        "k": "g",
        "b": "1Meq",
        "l": "1 Meqabyan",
        "c": 36,
        "e": "none"
      }
    ]
  },
  {
    "i": "2-3-meqabyan",
    "n": "II and III Meqabyan",
    "g": "መጽሐፈ መቃብያን ካልእ ወሳልስ",
    "s": "ethiopian",
    "t": "old",
    "p": [
      {
        "k": "g",
        "b": "3Meq",
        "l": "3 Meqabyan",
        "c": 10,
        "e": "none"
      }
    ]
  },
  {
    "i": "job",
    "n": "Job",
    "g": "መጽሐፈ ኢዮብ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JOB",
        "l": "Job",
        "c": 42
      }
    ]
  },
  {
    "i": "psalms",
    "n": "Psalms",
    "g": "መዝሙረ ዳዊት",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "PSA",
        "l": "Psalms",
        "c": 150
      }
    ]
  },
  {
    "i": "proverbs",
    "n": "Proverbs",
    "g": "መጽሐፈ ምሳሌ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "PRO",
        "l": "Proverbs",
        "c": 31
      }
    ]
  },
  {
    "i": "wisdom",
    "n": "Metsihafe Tibeb (Wisdom)",
    "g": "መጽሐፈ ጥበብ",
    "s": "deuterocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "WIS",
        "l": "Wisdom of Solomon",
        "c": 19
      }
    ]
  },
  {
    "i": "ecclesiastes",
    "n": "Ecclesiastes",
    "g": "መጽሐፈ መክብብ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "ECC",
        "l": "Ecclesiastes",
        "c": 12
      }
    ]
  },
  {
    "i": "song-of-songs",
    "n": "The Song of Songs",
    "g": "ማሕልየ መሓልይ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "SNG",
        "l": "Song of Solomon",
        "c": 8
      }
    ]
  },
  {
    "i": "isaiah",
    "n": "Isaiah",
    "g": "ትንቢት ኢሳይያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "ISA",
        "l": "Isaiah",
        "c": 66
      }
    ]
  },
  {
    "i": "jeremiah",
    "n": "Jeremiah",
    "g": "ትንቢት ኤርምያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JER",
        "l": "Jeremiah",
        "c": 52
      },
      {
        "k": "a",
        "b": "LAM",
        "l": "Lamentations",
        "c": 5
      },
      {
        "k": "a",
        "b": "BAR",
        "l": "Baruch",
        "c": 5
      }
    ]
  },
  {
    "i": "ezekiel",
    "n": "Ezekiel",
    "g": "ትንቢት ሄዜቅኤል",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "EZK",
        "l": "Ezekiel",
        "c": 48
      }
    ]
  },
  {
    "i": "daniel",
    "n": "Daniel",
    "g": "ትንቢት ዳንኤል",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "DAN",
        "l": "Daniel",
        "c": 12
      },
      {
        "k": "a",
        "b": "SUS",
        "l": "Susanna",
        "c": 1
      },
      {
        "k": "a",
        "b": "BEL",
        "l": "Bel and the Dragon",
        "c": 1
      },
      {
        "k": "a",
        "b": "S3Y",
        "l": "The Prayer of Azariah",
        "c": 1
      }
    ]
  },
  {
    "i": "hosea",
    "n": "Hosea",
    "g": "ትንቢት ሆሴዕ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "HOS",
        "l": "Hosea",
        "c": 14
      }
    ]
  },
  {
    "i": "amos",
    "n": "Amos",
    "g": "ትንቢት አሞጽ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "AMO",
        "l": "Amos",
        "c": 9
      }
    ]
  },
  {
    "i": "micah",
    "n": "Micah",
    "g": "ትንቢት ሚኪያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "MIC",
        "l": "Micah",
        "c": 7
      }
    ]
  },
  {
    "i": "joel",
    "n": "Joel",
    "g": "ትንቢት ኢያኤል",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JOL",
        "l": "Joel",
        "c": 3
      }
    ]
  },
  {
    "i": "obadiah",
    "n": "Obadiah",
    "g": "ትንቢት አብዲዮ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "OBA",
        "l": "Obadiah",
        "c": 1
      }
    ]
  },
  {
    "i": "jonah",
    "n": "Jonah",
    "g": "ትንቢት ዮናስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "JON",
        "l": "Jonah",
        "c": 4
      }
    ]
  },
  {
    "i": "nahum",
    "n": "Nahum",
    "g": "ትንቢት ናዘም",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "NAM",
        "l": "Nahum",
        "c": 3
      }
    ]
  },
  {
    "i": "habakkuk",
    "n": "Habakkuk",
    "g": "ትንቢት እንባቁም",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "HAB",
        "l": "Habakkuk",
        "c": 3
      }
    ]
  },
  {
    "i": "zephaniah",
    "n": "Zephaniah",
    "g": "ትንቢት ሶፈኒያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "ZEP",
        "l": "Zephaniah",
        "c": 3
      }
    ]
  },
  {
    "i": "haggai",
    "n": "Haggai",
    "g": "ትንቢት ሓጊ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "HAG",
        "l": "Haggai",
        "c": 2
      }
    ]
  },
  {
    "i": "zechariah",
    "n": "Zechariah",
    "g": "ትንቢት ዘካርያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "ZEC",
        "l": "Zechariah",
        "c": 14
      }
    ]
  },
  {
    "i": "malachi",
    "n": "Malachi",
    "g": "ትንቢት ሚልኪያስ",
    "s": "protocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "MAL",
        "l": "Malachi",
        "c": 4
      }
    ]
  },
  {
    "i": "sirach",
    "n": "Sirach",
    "g": "መጽሐፈ ሲራክ",
    "s": "deuterocanonical",
    "t": "old",
    "p": [
      {
        "k": "a",
        "b": "SIR",
        "l": "Sirach",
        "c": 51
      }
    ]
  },
  {
    "i": "matthew",
    "n": "Matthew",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "MAT",
        "l": "Matthew",
        "c": 28
      }
    ]
  },
  {
    "i": "mark",
    "n": "Mark",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "MRK",
        "l": "Mark",
        "c": 16
      }
    ]
  },
  {
    "i": "luke",
    "n": "Luke",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "LUK",
        "l": "Luke",
        "c": 24
      }
    ]
  },
  {
    "i": "john",
    "n": "John",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "JHN",
        "l": "John",
        "c": 21
      }
    ]
  },
  {
    "i": "acts",
    "n": "Acts",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "ACT",
        "l": "Acts",
        "c": 28
      }
    ]
  },
  {
    "i": "romans",
    "n": "Romans",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "ROM",
        "l": "Romans",
        "c": 16
      }
    ]
  },
  {
    "i": "1-corinthians",
    "n": "1 Corinthians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "1CO",
        "l": "1 Corinthians",
        "c": 16
      }
    ]
  },
  {
    "i": "2-corinthians",
    "n": "2 Corinthians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "2CO",
        "l": "2 Corinthians",
        "c": 13
      }
    ]
  },
  {
    "i": "galatians",
    "n": "Galatians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "GAL",
        "l": "Galatians",
        "c": 6
      }
    ]
  },
  {
    "i": "ephesians",
    "n": "Ephesians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "EPH",
        "l": "Ephesians",
        "c": 6
      }
    ]
  },
  {
    "i": "philippians",
    "n": "Philippians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "PHP",
        "l": "Philippians",
        "c": 4
      }
    ]
  },
  {
    "i": "colossians",
    "n": "Colossians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "COL",
        "l": "Colossians",
        "c": 4
      }
    ]
  },
  {
    "i": "1-thessalonians",
    "n": "1 Thessalonians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "1TH",
        "l": "1 Thessalonians",
        "c": 5
      }
    ]
  },
  {
    "i": "2-thessalonians",
    "n": "2 Thessalonians",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "2TH",
        "l": "2 Thessalonians",
        "c": 3
      }
    ]
  },
  {
    "i": "1-timothy",
    "n": "1 Timothy",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "1TI",
        "l": "1 Timothy",
        "c": 6
      }
    ]
  },
  {
    "i": "2-timothy",
    "n": "2 Timothy",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "2TI",
        "l": "2 Timothy",
        "c": 4
      }
    ]
  },
  {
    "i": "titus",
    "n": "Titus",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "TIT",
        "l": "Titus",
        "c": 3
      }
    ]
  },
  {
    "i": "philemon",
    "n": "Philemon",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "PHM",
        "l": "Philemon",
        "c": 1
      }
    ]
  },
  {
    "i": "hebrews",
    "n": "Hebrews",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "HEB",
        "l": "Hebrews",
        "c": 13
      }
    ]
  },
  {
    "i": "james",
    "n": "James",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "JAS",
        "l": "James",
        "c": 5
      }
    ]
  },
  {
    "i": "1-peter",
    "n": "1 Peter",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "1PE",
        "l": "1 Peter",
        "c": 5
      }
    ]
  },
  {
    "i": "2-peter",
    "n": "2 Peter",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "2PE",
        "l": "2 Peter",
        "c": 3
      }
    ]
  },
  {
    "i": "1-john",
    "n": "1 John",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "1JN",
        "l": "1 John",
        "c": 5
      }
    ]
  },
  {
    "i": "2-john",
    "n": "2 John",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "2JN",
        "l": "2 John",
        "c": 1
      }
    ]
  },
  {
    "i": "3-john",
    "n": "3 John",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "3JN",
        "l": "3 John",
        "c": 1
      }
    ]
  },
  {
    "i": "jude",
    "n": "Jude",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "JUD",
        "l": "Jude",
        "c": 1
      }
    ]
  },
  {
    "i": "revelation",
    "n": "Revelation",
    "s": "protocanonical",
    "t": "new",
    "p": [
      {
        "k": "a",
        "b": "REV",
        "l": "Revelation",
        "c": 22
      }
    ]
  },
  {
    "i": "sirate-tsion",
    "n": "Sirate Tsion (Order of Zion)",
    "g": "ስርዓተ ጽይዎን",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "Sinod",
        "l": "Sinodos",
        "c": 36,
        "e": "none"
      }
    ]
  },
  {
    "i": "tizaz",
    "n": "Tizaz (The Commandment)",
    "g": "ትዕዛዝ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "Sinod",
        "l": "Sinodos",
        "c": 36,
        "e": "none"
      }
    ]
  },
  {
    "i": "gitsew",
    "n": "Gitsew",
    "g": "ግጽወ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "Sinod",
        "l": "Sinodos",
        "c": 36,
        "e": "none"
      }
    ]
  },
  {
    "i": "abtilis",
    "n": "Abtilis",
    "g": "አብትሊስ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "Sinod",
        "l": "Sinodos",
        "c": 36,
        "e": "none"
      }
    ]
  },
  {
    "i": "1-dominos",
    "n": "The I Book of Dominos",
    "g": "ኪዳን ዘእግዚእነ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "TestLd",
        "l": "Testament of Our Lord",
        "c": 60,
        "e": "none"
      }
    ]
  },
  {
    "i": "2-dominos",
    "n": "The II Book of Dominos",
    "g": "ኪዳን ዘእግዚእነ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "TestLd",
        "l": "Testament of Our Lord",
        "c": 60,
        "e": "none"
      }
    ]
  },
  {
    "i": "clement",
    "n": "The Book of Clement",
    "g": "ቀሌሜንጥስ",
    "s": "ethiopian",
    "t": "new",
    "p": [
      {
        "k": "g",
        "b": "Clem",
        "l": "Ethiopic Clement",
        "c": 67,
        "e": "none"
      }
    ]
  }
];
// </generated-canon>

const BIBLE_API = 'https://bible-api.com';
const GEEZ_DATA = 'https://cdn.jsdelivr.net/gh/LPettay/ethiopian-bible@main/public/data/chapters';

/**
 * Ordered by how quickly they finish, because the whole generation has to fit
 * inside the 60s function limit.
 *
 * `budgetMs` is how long one attempt at that model may run, measured on a
 * three-paragraph interpretation with roughly 2x headroom: super-120b ~15-17s,
 * kimi-k3 ~28s, gpt-oss-20b ~48s. A single flat cap does not work here --
 * 32s silently strangled anything slower than the primary.
 *
 * The 550B Ultra model the browser uses takes one to three minutes and cannot
 * be used here.
 *
 * NOTE: models on this endpoint are retired without warning and answer 410
 * "end of life" afterwards. `openai/gpt-oss-120b` and
 * `nvidia/nemotron-3-nano-30b-a3b` both went that way, which left the chain
 * with no working fallback at all -- every entry below was verified live when
 * it was added. If interpretations start failing, check this first.
 */
const MODELS = [
  {
    id: 'nvidia/nemotron-3-super-120b-a12b',
    label: 'Nemotron 3 Super',
    prefix: 'detailed thinking off\n\n',
    budgetMs: 30_000,
  },
  { id: 'moonshotai/kimi-k3', label: 'Kimi K3', prefix: '', budgetMs: 45_000 },
  { id: 'openai/gpt-oss-20b', label: 'GPT-OSS 20B', prefix: '', budgetMs: 55_000 },
];

/** The chain's fastest member, for the one-sentence question top-up. */
const QUESTION_MODEL = MODELS[0];

/**
 * Verses in a passage-slot reading. Six was chosen when the passage rotated
 * hourly; now that it stands for a whole day there is room to raise it -- the
 * interpretation budget and WhatsApp's ~4096-character message limit both fit
 * comfortably past a dozen.
 */
const PASSAGE_VERSES = 6;

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const clean = (value: unknown): string => (typeof value === 'string' ? value.trim() : '');

/**
 * Scripture text only. bible-api returns verses with the source edition's hard
 * line breaks still in them ("I shall be a lady for ever:\nso that thou didst
 * not..."), which read as broken paragraphs in the app and as ragged text in a
 * WhatsApp message. Not applied to interpretations, where the blank lines
 * between paragraphs are meaningful.
 */
const collapse = (value: unknown): string => clean(value).replace(/\s+/g, ' ');

/** Stable 32-bit PRNG: the same key and slot select the same text everywhere. */
function seededRandom(seed: string): () => number {
  let hash = 2166136261;
  for (let index = 0; index < seed.length; index += 1) {
    hash ^= seed.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  let state = hash >>> 0;
  return () => {
    state += 0x6d2b79f5;
    let value = state;
    value = Math.imul(value ^ (value >>> 15), value | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
  };
}

export interface HourlyContent {
  text: string;
  reference: string;
  translation_id: string;
  translation_name: string;
  book_id: string;
  book_name: string;
  chapter: number;
  verse: number;
  type: 'verse' | 'passage';
  testament: 'old' | 'new';
  book: string;
  section: Section;
  geezName?: string;
  context?: { before: string; after: string; chapterReference: string };
}

/**
 * Picks and loads the reading for one (key, slot). Deterministic: given the
 * same inputs it always resolves to the same verses. The key is an hour key
 * for the hourly slots and a day key for the passage slot; the seeding does
 * not care which, it only needs a stable string.
 *
 * This base is the single-verse hourly reading. The parts that differ per slot
 * -- how many verses to take, which books are eligible, what the content calls
 * itself -- are the three protected methods below, so a slot that behaves
 * differently is its own subclass rather than a conditional threaded through
 * `load()`. See DailyPassageSelector and EthiopianSelector.
 */
class EditionSelector {
  protected readonly random: () => number;

  constructor(
    key: string,
    protected readonly slot: Slot,
  ) {
    this.random = seededRandom(`${key}:${slot}`);
  }

  /** How many consecutive verses this reading shows. */
  protected verseCount(): number {
    return 1;
  }

  /** What the reading calls itself to the client and to the interpreter. */
  protected contentType(): 'verse' | 'passage' {
    return 'verse';
  }

  /** Books eligible for this slot, excluding any with no English to show. */
  protected candidates(): CompactBook[] {
    return CANON.filter(EditionSelector.readable);
  }

  protected static readable(book: CompactBook): boolean {
    return book.p.some((part) => part.k === 'a' || part.e !== 'none');
  }

  /** Chapters we can show English for, as a prefix of the book's range. */
  private translatableChapters(book: CompactBook): number {
    let total = 0;
    for (const part of book.p) {
      if (part.k === 'g' && part.e === 'none') break;
      total += part.c;
    }
    return total;
  }

  private pickBook(): CompactBook {
    const books = this.candidates();
    const weights = books.map((book) => this.translatableChapters(book));
    const total = weights.reduce((sum, weight) => sum + weight, 0);

    let target = this.random() * total;
    for (let index = 0; index < books.length; index += 1) {
      target -= weights[index];
      if (target <= 0) return books[index];
    }
    return books[books.length - 1];
  }

  private resolve(book: CompactBook, chapter: number): { part: CompactPart; local: number } {
    let remaining = chapter;
    for (const part of book.p) {
      if (remaining <= part.c) return { part, local: remaining };
      remaining -= part.c;
    }
    return { part: book.p[0], local: 1 };
  }

  async load(): Promise<HourlyContent> {
    const book = this.pickBook();
    const span = this.translatableChapters(book);
    const chapter = 1 + Math.floor(this.random() * span);
    const { part, local } = this.resolve(book, chapter);

    const verses = part.k === 'a'
      ? await this.loadFromBibleApi(part, local)
      : await this.loadFromGeez(part, local);

    const usable = verses.filter((verse) => verse.text.length > 0);
    if (usable.length === 0) throw new Error(`${book.n} ${chapter} has no readable text`);

    const wanted = Math.min(this.verseCount(), usable.length);
    const start = Math.floor(this.random() * (usable.length - wanted + 1));
    const chosen = usable.slice(start, start + wanted);
    const first = chosen[0];
    const last = chosen[chosen.length - 1];

    const reference = chosen.length === 1
      ? `${part.l} ${local}:${first.verse}`
      : `${part.l} ${local}:${first.verse}-${last.verse}`;

    const index = usable.indexOf(first);
    const join = (list: typeof usable) => list.map((verse) => verse.text).join(' ');

    return {
      text: chosen.map((verse) => verse.text).join(' '),
      reference,
      translation_id: part.k === 'a' ? 'kjv' : 'geez',
      translation_name: part.k === 'a' ? 'King James Version' : 'Ge’ez sources',
      book_id: part.b,
      book_name: part.l,
      chapter: local,
      verse: first.verse,
      type: this.contentType(),
      testament: book.t,
      book: part.l,
      section: book.s,
      geezName: book.g,
      context: {
        before: join(usable.slice(Math.max(0, index - 4), index)),
        after: join(usable.slice(index + chosen.length, index + chosen.length + 4)),
        chapterReference: `${part.l} ${local}`,
      },
    };
  }

  private async loadFromBibleApi(part: CompactPart, chapter: number) {
    const response = await fetch(`${BIBLE_API}/data/kjv/${part.b}/${chapter}`);
    if (!response.ok) throw new Error(`bible-api ${response.status} for ${part.b} ${chapter}`);
    const data = (await response.json()) as { verses?: Array<{ text?: string; verse?: number }> };
    return (data.verses ?? []).map((verse, index) => ({
      verse: verse.verse ?? index + 1,
      text: collapse(verse.text),
    }));
  }

  private async loadFromGeez(part: CompactPart, chapter: number) {
    const response = await fetch(`${GEEZ_DATA}/${part.b}/${chapter}.json`);
    if (!response.ok) throw new Error(`jsDelivr ${response.status} for ${part.b} ${chapter}`);
    const data = (await response.json()) as {
      verses?: Array<{
        num: number | string;
        translation?: string;
        translations?: { lxx?: string; kjv?: string };
      }>;
    };
    return (data.verses ?? []).map((verse) => ({
      verse: Number(verse.num),
      text:
        collapse(verse.translation) ||
        collapse(verse.translations?.lxx) ||
        collapse(verse.translations?.kjv),
    }));
  }
}

/**
 * The daily passage: a run of verses rather than one, turning over at 6am
 * Eastern. This is the reading the family studies together and the one pushed
 * to WhatsApp each morning, so it is deliberately its own type -- its length,
 * its cadence (see CADENCE) and its interpretation prompt (which also asks for
 * a discussion question) all differ from the hourly readings.
 */
class DailyPassageSelector extends EditionSelector {
  constructor(key: string) {
    super(key, 'passage');
  }

  protected override verseCount(): number {
    return PASSAGE_VERSES;
  }

  protected override contentType(): 'verse' | 'passage' {
    return 'passage';
  }
}

/** The hourly reading drawn only from books outside the Protestant canon. */
class EthiopianSelector extends EditionSelector {
  constructor(key: string) {
    super(key, 'ethiopian');
  }

  protected override candidates(): CompactBook[] {
    return CANON.filter((book) => book.s !== 'protocanonical' && EditionSelector.readable(book));
  }
}

function selectorFor(key: string, slot: Slot): EditionSelector {
  if (slot === 'passage') return new DailyPassageSelector(key);
  if (slot === 'ethiopian') return new EthiopianSelector(key);
  return new EditionSelector(key, slot);
}

interface Interpretation {
  text: string;
  /** A discussion prompt. Only the daily passage produces one. */
  question: string | null;
  model: { id: string; label: string };
}

/**
 * Generates the interpretation, walking the model list until one answers.
 *
 * This base produces prose only. What the daily passage additionally needs --
 * a discussion question for the family group -- lives in
 * DailyPassageInterpreter, reached through the three hooks below, so the
 * hourly prompt is not disturbed by it.
 */
class Interpreter {
  constructor(protected readonly apiKey: string) {}

  /** Appended to the system prompt; empty for the hourly readings. */
  protected systemSuffix(): string {
    return '';
  }

  protected maxTokens(): number {
    return 2048;
  }

  /** Last chance to pull structure out of the raw completion. */
  protected async finish(raw: string, _deadline: number, _content: HourlyContent) {
    return { text: raw, question: null as string | null };
  }

  protected messages(content: HourlyContent): { system: string; user: string } {
    const geez = content.geezName ? ` Its Ge’ez title is ${content.geezName}.` : '';
    const canon =
      content.section === 'ethiopian'
        ? ` This passage is from a book canonical in the Ethiopian Orthodox Tewahedo Church and not found in the Protestant or Catholic canons.${geez} Interpret it from within that tradition, noting briefly why it is received there.`
        : content.section === 'deuterocanonical'
          ? ` This passage is deuterocanonical: received by the Ethiopian Orthodox Tewahedo, Catholic, and Eastern Orthodox churches, though not in the Protestant canon.${geez}`
          : geez;

    const system = `You are a biblical scholar and historian writing for a reader of the Ethiopian Orthodox Tewahedo Bible. You know the historical setting of each book, the literary shape of its argument, and the tradition that received it.${canon}

Write three short paragraphs, with no headings and no bullet points. First, place the passage in its historical setting, naming the period, place, audience, and relevant political or religious pressure where known. Second, explain what happens in the supplied surrounding verses and how the passage connects to them, including an original-language detail or custom only when it materially helps. Third, draw out its meaning for a reader today, grounded in that setting. Be specific; do not write generic encouragement or merely restate the verse. State uncertainty rather than inventing detail.${this.systemSuffix()}`;

    let user = `Interpret this Bible ${content.type} from ${content.reference}:\n\n"${content.text}"`;
    if (content.context?.before || content.context?.after) {
      user += `\n\nSurrounding text from ${content.context.chapterReference}:`;
      if (content.context.before) user += `\n\nImmediately before:\n"${content.context.before}"`;
      if (content.context.after) user += `\n\nImmediately after:\n"${content.context.after}"`;
      user += '\n\nUse this context, but interpret only the selected passage.';
    }

    return { system, user };
  }

  protected transient(status: number, message: string): boolean {
    return (
      status === 429 ||
      status >= 500 ||
      /overload|temporarily unavailable|not ready to serve|try again|capacity|timed? ?out/i.test(message)
    );
  }

  async run(content: HourlyContent, deadline: number): Promise<Interpretation> {
    const { system, user } = this.messages(content);
    let lastError = 'no model attempted';

    for (const model of MODELS) {
      for (let attempt = 1; attempt <= 2; attempt += 1) {
        if (Date.now() > deadline) throw new Error('Out of time generating interpretation');

        try {

        // Bound each attempt so one slow model cannot consume the whole 60s
        // function budget, but bound it by what that model actually needs --
        // see budgetMs. Generations run longer from Vercel's region than
        // locally, hence the headroom.
        const remaining = Math.max(1000, Math.min(model.budgetMs, deadline - Date.now()));

        const response = await fetch('https://integrate.api.nvidia.com/v1/chat/completions', {
          method: 'POST',
          signal: AbortSignal.timeout(remaining),
          headers: {
            Authorization: `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            model: model.id,
            messages: [
              { role: 'system', content: model.prefix + system },
              { role: 'user', content: user },
            ],
            max_tokens: this.maxTokens(),
            temperature: 0.7,
          }),
        });

        if (!response.ok) {
          lastError = `${model.id}: HTTP ${response.status}`;
          const body = (await response.text()).slice(0, 200);
          if (this.transient(response.status, body) && attempt === 1) {
            await sleep(2000);
            continue;
          }
          break;
        }

        const data = (await response.json()) as {
          choices?: Array<{ message?: { content?: string } }>;
        };
        const text = clean(data.choices?.[0]?.message?.content);
        if (text) {
          const parsed = await this.finish(text, deadline, content);
          return { ...parsed, model: { id: model.id, label: model.label } };
        }

        lastError = `${model.id}: empty response`;
        } catch (error) {
          // Includes the per-attempt timeout above; move on to the next model.
          lastError = `${model.id}: ${(error as Error).message}`;
          break;
        }
      }
    }

    throw new Error(lastError);
  }
}

/**
 * Models bold the sentinel unprompted and sometimes indent it, so match
 * loosely. Anchored to a line start so a "QUESTION:" inside the prose itself
 * cannot be mistaken for the delimiter.
 */
const QUESTION_SENTINEL = /^[ \t]*\**\s*QUESTION\s*\**[ \t]*:[ \t]*(.+?)[ \t]*$/im;

/**
 * The daily passage's interpreter. Beyond the prose it asks for one discussion
 * question, which is sent to the family group as its own message.
 *
 * The question rides along on the same completion behind a sentinel line
 * rather than arriving as JSON or as a second call. JSON mode is not
 * uniformly supported across the three models in MODELS, and a failed parse
 * would cost the whole interpretation; a second round trip costs 7-20s against
 * a 55s deadline that already budgets 32s per attempt. A sentinel costs
 * nothing and degrades to `question: null`.
 */
class DailyPassageInterpreter extends Interpreter {
  protected override systemSuffix(): string {
    return (
      '\n\nAfter the three paragraphs, write one final line beginning exactly with' +
      ' "QUESTION:" followed by a single open-ended question of fewer than 25 words' +
      ' that a family could discuss together. Ask what the passage asks of the reader;' +
      ' do not ask for facts the paragraphs already state. Write nothing after that line.'
    );
  }

  /** Slightly above the base, so the sentinel is not cut off mid-question. */
  protected override maxTokens(): number {
    return 2200;
  }

  protected override async finish(raw: string, deadline: number, content: HourlyContent) {
    const match = raw.match(QUESTION_SENTINEL);
    if (match && match.index !== undefined) {
      return {
        text: raw.slice(0, match.index).trim(),
        question: match[1].replace(/\*\*/g, '').trim() || null,
      };
    }

    // The model ignored the format. One cheap top-up beats losing the message,
    // but only if there is comfortably enough budget left to spend on it.
    const question = Date.now() < deadline - 12_000 ? await this.topUp(content) : null;
    return { text: raw.trim(), question };
  }

  private async topUp(content: HourlyContent): Promise<string | null> {
    try {
      const response = await fetch('https://integrate.api.nvidia.com/v1/chat/completions', {
        method: 'POST',
        signal: AbortSignal.timeout(10_000),
        headers: { Authorization: `Bearer ${this.apiKey}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          // The fastest model in the chain; this only has to write one sentence.
          model: QUESTION_MODEL.id,
          messages: [
            {
              role: 'system',
              content:
                QUESTION_MODEL.prefix +
                'Reply with one open-ended question of fewer than 25 words' +
                ' that a family could discuss together about the passage. Output the question alone,' +
                ' with no preamble, label, or quotation marks.',
            },
            { role: 'user', content: `${content.reference}\n\n"${content.text}"` },
          ],
          max_tokens: 120,
          temperature: 0.6,
        }),
      });
      if (!response.ok) return null;
      const data = (await response.json()) as { choices?: Array<{ message?: { content?: string } }> };
      return clean(data.choices?.[0]?.message?.content).split('\n')[0].trim() || null;
    } catch (error) {
      console.warn('Question top-up failed:', (error as Error).message);
      return null;
    }
  }
}

function interpreterFor(slot: Slot, apiKey: string): Interpreter {
  return slot === 'passage' ? new DailyPassageInterpreter(apiKey) : new Interpreter(apiKey);
}

/** Collapses concurrent requests for the same edition into one generation. */
const inflight = new Map<string, Promise<unknown>>();

function once<T>(key: string, factory: () => Promise<T>): Promise<T> {
  const running = inflight.get(key);
  if (running) return running as Promise<T>;
  const promise = factory().finally(() => inflight.delete(key));
  inflight.set(key, promise);
  return promise;
}

function hourKey(date = new Date()): string {
  return date.toISOString().slice(0, 13);
}

const EDITION_TZ = 'America/New_York';

/**
 * The editorial day, which rolls over at 6am Eastern rather than at UTC
 * midnight, so the passage is already settled when the morning reading goes
 * out. Intl is the timezone database here -- Node on Vercel ships full ICU, so
 * no tz library is needed and DST is handled by the runtime rather than by us.
 */
export function dayKey(date = new Date()): string {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: EDITION_TZ,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    hourCycle: 'h23',
  }).formatToParts(date);
  const at = (type: string) => parts.find((part) => part.type === type)?.value ?? '';
  const ymd = `${at('year')}-${at('month')}-${at('day')}`;
  // Before 6am Eastern, yesterday's edition is still the current one.
  return Number(at('hour')) >= 6 ? ymd : previousDayKey(ymd);
}

/**
 * Calendar arithmetic, deliberately -- NOT `new Date(now - 86_400_000)`.
 * Subtracting 24 hours of real time lands on the wrong editorial day for one
 * hour each spring: at 06:30 EDT on the spring-forward Sunday, 24h earlier is
 * 05:30 EST Saturday, which is before 6am and so resolves to *Friday*,
 * silently skipping Saturday's edition. Stepping the date string has no wall
 * clock to get wrong.
 */
export function previousDayKey(key: string): string {
  const [year, month, day] = key.split('-').map(Number);
  return new Date(Date.UTC(year, month - 1, day - 1)).toISOString().slice(0, 10);
}

/**
 * Which cadence each slot turns over on. The passage is the shared daily
 * reading; the other two stay hourly so the page still moves between days.
 */
const CADENCE: Record<Slot, 'hour' | 'day'> = {
  verse: 'hour',
  passage: 'day',
  ethiopian: 'hour',
};

function editionKeyFor(slot: Slot, date = new Date()): string {
  return CADENCE[slot] === 'day' ? dayKey(date) : hourKey(date);
}

/** The edition immediately before `current`, in that slot's own cadence. */
function priorKeyFor(slot: Slot, current: string): string {
  return CADENCE[slot] === 'day'
    ? previousDayKey(current)
    : hourKey(new Date(Date.now() - 3_600_000));
}

/**
 * How long the edge may keep a response. The edition key is part of the URL,
 * so every response is immutable content at a unique address and the TTL can
 * safely exceed the cadence -- a week for the daily passage costs nothing and
 * survives a warm failure.
 */
const CDN_TTL: Record<Slot, number> = {
  verse: 3_600,
  ethiopian: 3_600,
  passage: 604_800,
};

/**
 * `cache` is the slot whose policy applies, or false for "do not store". Only
 * a complete edition is ever passed a slot -- see the note at the return of
 * GET, which matters more now that a frozen failure would last a day.
 */
function json(body: unknown, status = 200, cache: Slot | false = false): Response {
  const browserMaxAge = cache && CADENCE[cache] === 'day' ? 600 : 60;
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'Content-Type': 'application/json',
      // The CDN copy is what makes the edition shared: one generation per
      // edition key is reused for every visitor until that key rolls over.
      'Cache-Control': cache ? `public, max-age=${browserMaxAge}` : 'no-store',
      ...(cache
        ? {
            'Vercel-CDN-Cache-Control':
              `public, s-maxage=${CDN_TTL[cache]}, stale-while-revalidate=604800, stale-if-error=604800`,
          }
        : {}),
    },
  });
}

/**
 * Exported as a named `GET` rather than `export default`.
 *
 * Under Vercel's Node runtime a default export is treated as the legacy
 * `(req, res) => void` signature and any returned `Response` is silently
 * discarded -- the function then never responds and is killed at the 60s
 * timeout. A named HTTP-method export opts into the Web fetch-style API.
 */
export async function GET(request: Request): Promise<Response> {
  const deadline = Date.now() + 55_000;
  // Under Vercel's Node runtime `request.url` is a path ("/api/hourly?..."),
  // not an absolute URL as it would be on the edge runtime, so URL needs a
  // base to parse against.
  const url = new URL(request.url, 'http://localhost');
  const slot = (url.searchParams.get('slot') ?? 'verse') as Slot;

  if (!['verse', 'passage', 'ethiopian'].includes(slot)) {
    return json({ error: 'Unknown slot' }, 400);
  }

  // `hour` is the pre-daily name for this parameter, kept so a tab left open
  // across the rollout keeps working.
  const supplied = url.searchParams.get('key') ?? url.searchParams.get('hour');

  // No key: redirect to the canonical keyed URL rather than serving content
  // here.
  //
  // Serving it directly meant this URL got the slot's cache policy, which for
  // the passage is a week -- so "give me the current passage" would have
  // answered with one particular day's reading for seven days. It also means
  // index.html can fire these requests before the bundle has even downloaded
  // without needing its own copy of the key arithmetic: the redirect lands on
  // the keyed URL, the browser caches it there, and the app's own request for
  // that same URL is then served from cache.
  if (!supplied) {
    const canonical = `/api/hourly?key=${editionKeyFor(slot)}&slot=${slot}`;
    return new Response(null, {
      status: 302,
      headers: {
        Location: canonical,
        // Briefly, so the pointer cannot outlive a rollover by long.
        'Cache-Control': 'public, max-age=30',
        'Vercel-CDN-Cache-Control': 'public, s-maxage=30',
      },
    });
  }

  let requested = supplied;

  // COMPAT: bundles cached before the daily rollout still send an hour key for
  // the passage slot. Coerce rather than reject, so a stale tab sees today's
  // passage instead of an error. Remove once the v5 localStorage generation
  // has aged out.
  if (CADENCE[slot] === 'day' && requested.length === 13) {
    requested = dayKey(new Date(`${requested}:00:00Z`));
  }

  // Only the current or previous edition, so a crawler cannot walk arbitrary
  // keys and manufacture unlimited model calls.
  const current = editionKeyFor(slot);
  if (requested !== current && requested !== priorKeyFor(slot, current)) {
    return json({ error: 'Edition expired' }, 400);
  }

  try {
    const content = await once(`content:${requested}:${slot}`, () =>
      selectorFor(requested, slot).load(),
    );

    // `hour` is echoed alongside `key` for the same one-deploy reason as above.
    const envelope = { key: requested, hour: requested, slot, content };

    if (!process.env.NVIDIA_API_KEY) {
      return json({ ...envelope, interpretation: null }, 200, slot);
    }

    const interpretation = await once(`interpretation:${requested}:${slot}`, () =>
      interpreterFor(slot, process.env.NVIDIA_API_KEY as string).run(content, deadline),
    ).catch((error: Error) => {
      console.warn('Interpretation failed:', error.message);
      return null;
    });

    // Only a complete edition is allowed into the shared CDN cache. Caching a
    // failed generation would freeze "interpretation unavailable" in place for
    // every visitor until the key rolls over -- which for the daily passage is
    // a whole day, so this matters more than it used to. Leaving it uncached
    // lets the next request try again.
    return json({ ...envelope, interpretation }, 200, interpretation !== null ? slot : false);
  } catch (error) {
    return json({ error: (error as Error).message }, 502);
  }
}
